package com.jesus.cineapp.pojos;
// Generated 14/03/2018 12:15:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalles generated by hbm2java
 */
public class Detalles  implements java.io.Serializable {


     private BigDecimal idDetalle;
     private Peliculas peliculas;
     private String director;
     private String actores;
     private String urlTrailer;
     private String sinopsis;

    public Detalles() {
    }

	
    public Detalles(BigDecimal idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Detalles(BigDecimal idDetalle, Peliculas peliculas, String director, String actores, String urlTrailer, String sinopsis) {
       this.idDetalle = idDetalle;
       this.peliculas = peliculas;
       this.director = director;
       this.actores = actores;
       this.urlTrailer = urlTrailer;
       this.sinopsis = sinopsis;
    }
   
    public BigDecimal getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(BigDecimal idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public String getActores() {
        return this.actores;
    }
    
    public void setActores(String actores) {
        this.actores = actores;
    }
    public String getUrlTrailer() {
        return this.urlTrailer;
    }
    
    public void setUrlTrailer(String urlTrailer) {
        this.urlTrailer = urlTrailer;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }




}


