package com.jesus.cineapp.pojos;
// Generated 9/04/2018 04:30:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalles generated by hbm2java
 */
@Entity
@Table(name="DETALLES"
    ,schema="CINE"
)
public class Detalles  implements java.io.Serializable {


     private BigDecimal idDetalle;
     private Peliculas peliculas;
     private String director;
     private String actores;
     private String urlTrailer;
     private String sinopsis;

    public Detalles() {
    }

	
    public Detalles(BigDecimal idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Detalles(BigDecimal idDetalle, Peliculas peliculas, String director, String actores, String urlTrailer, String sinopsis) {
       this.idDetalle = idDetalle;
       this.peliculas = peliculas;
       this.director = director;
       this.actores = actores;
       this.urlTrailer = urlTrailer;
       this.sinopsis = sinopsis;
    }
   
     @Id 

    
    @Column(name="ID_DETALLE", nullable=false, precision=22, scale=0)
    public BigDecimal getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(BigDecimal idDetalle) {
        this.idDetalle = idDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PELICULA")
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }

    
    @Column(name="DIRECTOR", length=20)
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }

    
    @Column(name="ACTORES", length=20)
    public String getActores() {
        return this.actores;
    }
    
    public void setActores(String actores) {
        this.actores = actores;
    }

    
    @Column(name="URL_TRAILER", length=18)
    public String getUrlTrailer() {
        return this.urlTrailer;
    }
    
    public void setUrlTrailer(String urlTrailer) {
        this.urlTrailer = urlTrailer;
    }

    
    @Column(name="SINOPSIS", length=18)
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }




}


