package com.jesus.cineapp.pojos;
// Generated 15/03/2018 05:46:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horarios generated by hbm2java
 */
public class Horarios  implements java.io.Serializable {


     private BigDecimal idHorario;
     private Salas salas;
     private Date fecha;
     private String hora;
     private Set<RelPeliculasHorarios> relPeliculasHorarioses = new HashSet<RelPeliculasHorarios>(0);

    public Horarios() {
    }

	
    public Horarios(BigDecimal idHorario) {
        this.idHorario = idHorario;
    }
    public Horarios(BigDecimal idHorario, Salas salas, Date fecha, String hora, Set<RelPeliculasHorarios> relPeliculasHorarioses) {
       this.idHorario = idHorario;
       this.salas = salas;
       this.fecha = fecha;
       this.hora = hora;
       this.relPeliculasHorarioses = relPeliculasHorarioses;
    }
   
    public BigDecimal getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(BigDecimal idHorario) {
        this.idHorario = idHorario;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public Set<RelPeliculasHorarios> getRelPeliculasHorarioses() {
        return this.relPeliculasHorarioses;
    }
    
    public void setRelPeliculasHorarioses(Set<RelPeliculasHorarios> relPeliculasHorarioses) {
        this.relPeliculasHorarioses = relPeliculasHorarioses;
    }




}


