package com.jesus.cineapp.pojos;
// Generated 9/04/2018 04:30:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * Horarios generated by hbm2java
 */
@Entity
@Table(name="HORARIOS"
    ,schema="CINE"
)
public class Horarios  implements java.io.Serializable {


     private BigDecimal idHorario;
     private Salas salas;
     private Date fecha;
     private String hora;
     private Set relPeliculasHorarioses = new HashSet(0);

    public Horarios() {
    }

    public Horarios(Salas salas, Date fecha, String hora, Set relPeliculasHorarioses) {
       this.salas = salas;
       this.fecha = fecha;
       this.hora = hora;
       this.relPeliculasHorarioses = relPeliculasHorarioses;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID_HORARIO", nullable=false, precision=22, scale=0)
    public BigDecimal getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(BigDecimal idHorario) {
        this.idHorario = idHorario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SALA")
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="HORA", length=20)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="horarios")
    public Set getRelPeliculasHorarioses() {
        return this.relPeliculasHorarioses;
    }
    
    public void setRelPeliculasHorarioses(Set relPeliculasHorarioses) {
        this.relPeliculasHorarioses = relPeliculasHorarioses;
    }




}


