package com.jesus.cineapp.pojos;
// Generated 9/04/2018 04:30:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Noticias generated by hbm2java
 */
@Entity
@Table(name="NOTICIAS"
    ,schema="CINE"
)
public class Noticias  implements java.io.Serializable {


     private BigDecimal idNoticia;
     private Peliculas peliculas;
     private String titulo;
     private String detalle;
     private String estatus;

    public Noticias() {
    }

	
    public Noticias(BigDecimal idNoticia, Peliculas peliculas) {
        this.idNoticia = idNoticia;
        this.peliculas = peliculas;
    }
    public Noticias(BigDecimal idNoticia, Peliculas peliculas, String titulo, String detalle, String estatus) {
       this.idNoticia = idNoticia;
       this.peliculas = peliculas;
       this.titulo = titulo;
       this.detalle = detalle;
       this.estatus = estatus;
    }
   
     @Id 

    
    @Column(name="ID_NOTICIA", nullable=false, precision=22, scale=0)
    public BigDecimal getIdNoticia() {
        return this.idNoticia;
    }
    
    public void setIdNoticia(BigDecimal idNoticia) {
        this.idNoticia = idNoticia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PELICULA", nullable=false)
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }

    
    @Column(name="TITULO", length=20)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="DETALLE", length=20)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    
    @Column(name="ESTATUS", length=20)
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


