package com.jesus.cineapp.pojos;
// Generated 15/03/2018 05:46:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Noticias generated by hbm2java
 */
public class Noticias  implements java.io.Serializable {


     private BigDecimal idNoticia;
     private Peliculas peliculas;
     private String titulo;
     private String detalle;
     private String estatus;

    public Noticias() {
    }

	
    public Noticias(BigDecimal idNoticia, Peliculas peliculas) {
        this.idNoticia = idNoticia;
        this.peliculas = peliculas;
    }
    public Noticias(BigDecimal idNoticia, Peliculas peliculas, String titulo, String detalle, String estatus) {
       this.idNoticia = idNoticia;
       this.peliculas = peliculas;
       this.titulo = titulo;
       this.detalle = detalle;
       this.estatus = estatus;
    }
   
    public BigDecimal getIdNoticia() {
        return this.idNoticia;
    }
    
    public void setIdNoticia(BigDecimal idNoticia) {
        this.idNoticia = idNoticia;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


