package com.jesus.cineapp.pojos;
// Generated 14/03/2018 12:15:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas  implements java.io.Serializable {


     private BigDecimal idPelicula;
     private String titulo;
     private String genero;
     private String clasificacion;
     private BigDecimal duracion;
     private Date fechaEstreno;
     private String estatus;
     private String imagen;
     private Set<Detalles> detalleses = new HashSet<Detalles>(0);
     private Set<RelPeliculasHorarios> relPeliculasHorarioses = new HashSet<RelPeliculasHorarios>(0);
     private Set<Noticias> noticiases = new HashSet<Noticias>(0);

    public Peliculas() {
    }

	
    public Peliculas(BigDecimal idPelicula) {
        this.idPelicula = idPelicula;
    }
    public Peliculas(BigDecimal idPelicula, String titulo, String genero, String clasificacion, BigDecimal duracion, Date fechaEstreno, String estatus, String imagen, Set<Detalles> detalleses, Set<RelPeliculasHorarios> relPeliculasHorarioses, Set<Noticias> noticiases) {
       this.idPelicula = idPelicula;
       this.titulo = titulo;
       this.genero = genero;
       this.clasificacion = clasificacion;
       this.duracion = duracion;
       this.fechaEstreno = fechaEstreno;
       this.estatus = estatus;
       this.imagen = imagen;
       this.detalleses = detalleses;
       this.relPeliculasHorarioses = relPeliculasHorarioses;
       this.noticiases = noticiases;
    }
   
    public BigDecimal getIdPelicula() {
        return this.idPelicula;
    }
    
    public void setIdPelicula(BigDecimal idPelicula) {
        this.idPelicula = idPelicula;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
    public BigDecimal getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(BigDecimal duracion) {
        this.duracion = duracion;
    }
    public Date getFechaEstreno() {
        return this.fechaEstreno;
    }
    
    public void setFechaEstreno(Date fechaEstreno) {
        this.fechaEstreno = fechaEstreno;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set<Detalles> getDetalleses() {
        return this.detalleses;
    }
    
    public void setDetalleses(Set<Detalles> detalleses) {
        this.detalleses = detalleses;
    }
    public Set<RelPeliculasHorarios> getRelPeliculasHorarioses() {
        return this.relPeliculasHorarioses;
    }
    
    public void setRelPeliculasHorarioses(Set<RelPeliculasHorarios> relPeliculasHorarioses) {
        this.relPeliculasHorarioses = relPeliculasHorarioses;
    }
    public Set<Noticias> getNoticiases() {
        return this.noticiases;
    }
    
    public void setNoticiases(Set<Noticias> noticiases) {
        this.noticiases = noticiases;
    }




}


