package com.jesus.cineapp.pojos;
// Generated 9/04/2018 04:30:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Peliculas generated by hbm2java
 */
@Entity
@Table(name="PELICULAS"
    ,schema="CINE"
)
public class Peliculas  implements java.io.Serializable {


     private BigDecimal idPelicula;
     private String titulo;
     private String genero;
     private String clasificacion;
     private BigDecimal duracion;
     private Date fechaEstreno;
     private String estatus;
     private String imagen;
     private Set detalleses = new HashSet(0);
     private Set relPeliculasHorarioses = new HashSet(0);
     private Set noticiases = new HashSet(0);

    public Peliculas() {
    }

	
    public Peliculas(BigDecimal idPelicula) {
        this.idPelicula = idPelicula;
    }
    public Peliculas(BigDecimal idPelicula, String titulo, String genero, String clasificacion, BigDecimal duracion, Date fechaEstreno, String estatus, String imagen, Set detalleses, Set relPeliculasHorarioses, Set noticiases) {
       this.idPelicula = idPelicula;
       this.titulo = titulo;
       this.genero = genero;
       this.clasificacion = clasificacion;
       this.duracion = duracion;
       this.fechaEstreno = fechaEstreno;
       this.estatus = estatus;
       this.imagen = imagen;
       this.detalleses = detalleses;
       this.relPeliculasHorarioses = relPeliculasHorarioses;
       this.noticiases = noticiases;
    }
   
     @Id 

    
    @Column(name="ID_PELICULA", nullable=false, precision=22, scale=0)
    public BigDecimal getIdPelicula() {
        return this.idPelicula;
    }
    
    public void setIdPelicula(BigDecimal idPelicula) {
        this.idPelicula = idPelicula;
    }

    
    @Column(name="TITULO", length=20)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="GENERO", length=20)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="CLASIFICACION", length=20)
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }

    
    @Column(name="DURACION", precision=22, scale=0)
    public BigDecimal getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(BigDecimal duracion) {
        this.duracion = duracion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ESTRENO", length=7)
    public Date getFechaEstreno() {
        return this.fechaEstreno;
    }
    
    public void setFechaEstreno(Date fechaEstreno) {
        this.fechaEstreno = fechaEstreno;
    }

    
    @Column(name="ESTATUS", length=20)
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    
    @Column(name="IMAGEN", length=20)
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="peliculas")
    public Set getDetalleses() {
        return this.detalleses;
    }
    
    public void setDetalleses(Set detalleses) {
        this.detalleses = detalleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="peliculas")
    public Set getRelPeliculasHorarioses() {
        return this.relPeliculasHorarioses;
    }
    
    public void setRelPeliculasHorarioses(Set relPeliculasHorarioses) {
        this.relPeliculasHorarioses = relPeliculasHorarioses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="peliculas")
    public Set getNoticiases() {
        return this.noticiases;
    }
    
    public void setNoticiases(Set noticiases) {
        this.noticiases = noticiases;
    }




}


