package com.jesus.cineapp.pojos;
// Generated 9/04/2018 04:30:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name="PERFIL"
    ,schema="CINE"
)
public class Perfil  implements java.io.Serializable {


     private BigDecimal idPerfil;
     private String descripcion;
     private Set usuarioses = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(BigDecimal idPerfil) {
        this.idPerfil = idPerfil;
    }
    public Perfil(BigDecimal idPerfil, String descripcion, Set usuarioses) {
       this.idPerfil = idPerfil;
       this.descripcion = descripcion;
       this.usuarioses = usuarioses;
    }
   
     @Id 

    
    @Column(name="ID_PERFIL", nullable=false, precision=22, scale=0)
    public BigDecimal getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(BigDecimal idPerfil) {
        this.idPerfil = idPerfil;
    }

    
    @Column(name="DESCRIPCION", length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perfil")
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


