package com.jesus.cineapp.pojos;
// Generated 15/03/2018 05:46:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RelPeliculasHorarios generated by hbm2java
 */
public class RelPeliculasHorarios  implements java.io.Serializable {


     private BigDecimal idRelPeliculasHorarios;
     private Horarios horarios;
     private Peliculas peliculas;

    public RelPeliculasHorarios() {
    }

	
    public RelPeliculasHorarios(BigDecimal idRelPeliculasHorarios, Peliculas peliculas) {
        this.idRelPeliculasHorarios = idRelPeliculasHorarios;
        this.peliculas = peliculas;
    }
    public RelPeliculasHorarios(BigDecimal idRelPeliculasHorarios, Horarios horarios, Peliculas peliculas) {
       this.idRelPeliculasHorarios = idRelPeliculasHorarios;
       this.horarios = horarios;
       this.peliculas = peliculas;
    }
   
    public BigDecimal getIdRelPeliculasHorarios() {
        return this.idRelPeliculasHorarios;
    }
    
    public void setIdRelPeliculasHorarios(BigDecimal idRelPeliculasHorarios) {
        this.idRelPeliculasHorarios = idRelPeliculasHorarios;
    }
    public Horarios getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Horarios horarios) {
        this.horarios = horarios;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }




}


