package com.jesus.cineapp.pojos;
// Generated 9/04/2018 04:30:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * RelPeliculasHorarios generated by hbm2java
 */
@Entity
@Table(name="REL_PELICULAS_HORARIOS"
    ,schema="CINE"
)
public class RelPeliculasHorarios  implements java.io.Serializable {


     private BigDecimal idRelPeliculasHorarios;
     private Horarios horarios;
     private Peliculas peliculas;

    public RelPeliculasHorarios() {
    }

	
    public RelPeliculasHorarios(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public RelPeliculasHorarios(Horarios horarios, Peliculas peliculas) {
       this.horarios = horarios;
       this.peliculas = peliculas;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID_REL_PELICULAS_HORARIOS", nullable=false, precision=22, scale=0)
    public BigDecimal getIdRelPeliculasHorarios() {
        return this.idRelPeliculasHorarios;
    }
    
    public void setIdRelPeliculasHorarios(BigDecimal idRelPeliculasHorarios) {
        this.idRelPeliculasHorarios = idRelPeliculasHorarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_HORARIO")
    public Horarios getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Horarios horarios) {
        this.horarios = horarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PELICULA", nullable=false)
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }




}


