package com.jesus.cineapp.pojos;
// Generated 9/04/2018 04:30:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Salas generated by hbm2java
 */
@Entity
@Table(name="SALAS"
    ,schema="CINE"
)
public class Salas  implements java.io.Serializable {


     private BigDecimal idSala;
     private String nombreSala;
     private Double precio;
     private Set horarioses = new HashSet(0);

    public Salas() {
    }

	
    public Salas(BigDecimal idSala) {
        this.idSala = idSala;
    }
    public Salas(BigDecimal idSala, String nombreSala, Double precio, Set horarioses) {
       this.idSala = idSala;
       this.nombreSala = nombreSala;
       this.precio = precio;
       this.horarioses = horarioses;
    }
   
     @Id 

    
    @Column(name="ID_SALA", nullable=false, precision=38, scale=0)
    public BigDecimal getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(BigDecimal idSala) {
        this.idSala = idSala;
    }

    
    @Column(name="NOMBRE_SALA", length=20)
    public String getNombreSala() {
        return this.nombreSala;
    }
    
    public void setNombreSala(String nombreSala) {
        this.nombreSala = nombreSala;
    }

    
    @Column(name="PRECIO", precision=126, scale=0)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="salas")
    public Set getHorarioses() {
        return this.horarioses;
    }
    
    public void setHorarioses(Set horarioses) {
        this.horarioses = horarioses;
    }




}


