package com.jesus.cineapp.pojos;
// Generated 9/04/2018 04:30:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="USUARIOS"
    ,schema="CINE"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_USUARIO", "ID_PERFIL"}) 
)
public class Usuarios  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private Perfil perfil;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private String usuario;
     private String contrasenia;
     private String email;
     private String estatus;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public Usuarios() {
    }

    public Usuarios(Perfil perfil, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String usuario, String contrasenia, String email, String estatus, Date fechaRegistro, Date fechaModificacion) {
       this.perfil = perfil;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.email = email;
       this.estatus = estatus;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID_USUARIO", nullable=false, precision=22, scale=0)
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PERFIL")
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="PRIMER_NOMBRE", length=30)
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    
    @Column(name="SEGUNDO_NOMBRE", length=30)
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    
    @Column(name="PRIMER_APELLIDO", length=30)
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    
    @Column(name="SEGUNDO_APELLIDO", length=30)
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    
    @Column(name="USUARIO", length=30)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="CONTRASENIA", length=100)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="ESTATUS", length=20)
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_REGISTRO", length=7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MODIFICACION", length=7)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


